#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TA_RealEstate_Kel11
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RealEstate")]
	public partial class RealEstateDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertclient(client instance);
    partial void Updateclient(client instance);
    partial void Deleteclient(client instance);
    partial void Insertjabatan(jabatan instance);
    partial void Updatejabatan(jabatan instance);
    partial void Deletejabatan(jabatan instance);
    partial void InsertkategoriBayar(kategoriBayar instance);
    partial void UpdatekategoriBayar(kategoriBayar instance);
    partial void DeletekategoriBayar(kategoriBayar instance);
    partial void InsertkategoriCicilan(kategoriCicilan instance);
    partial void UpdatekategoriCicilan(kategoriCicilan instance);
    partial void DeletekategoriCicilan(kategoriCicilan instance);
    partial void Insertpegawai(pegawai instance);
    partial void Updatepegawai(pegawai instance);
    partial void Deletepegawai(pegawai instance);
    partial void Insertpemilik(pemilik instance);
    partial void Updatepemilik(pemilik instance);
    partial void Deletepemilik(pemilik instance);
    partial void Insertproperty(property instance);
    partial void Updateproperty(property instance);
    partial void Deleteproperty(property instance);
    partial void InsertpropertyTipe(propertyTipe instance);
    partial void UpdatepropertyTipe(propertyTipe instance);
    partial void DeletepropertyTipe(propertyTipe instance);
    partial void InserttPembelian(tPembelian instance);
    partial void UpdatetPembelian(tPembelian instance);
    partial void DeletetPembelian(tPembelian instance);
    #endregion
		
		public RealEstateDataContext() : 
				base(global::TA_RealEstate_Kel11.Properties.Settings.Default.RealEstateConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public RealEstateDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RealEstateDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RealEstateDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RealEstateDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<client> clients
		{
			get
			{
				return this.GetTable<client>();
			}
		}
		
		public System.Data.Linq.Table<jabatan> jabatans
		{
			get
			{
				return this.GetTable<jabatan>();
			}
		}
		
		public System.Data.Linq.Table<kategoriBayar> kategoriBayars
		{
			get
			{
				return this.GetTable<kategoriBayar>();
			}
		}
		
		public System.Data.Linq.Table<kategoriCicilan> kategoriCicilans
		{
			get
			{
				return this.GetTable<kategoriCicilan>();
			}
		}
		
		public System.Data.Linq.Table<pegawai> pegawais
		{
			get
			{
				return this.GetTable<pegawai>();
			}
		}
		
		public System.Data.Linq.Table<pemilik> pemiliks
		{
			get
			{
				return this.GetTable<pemilik>();
			}
		}
		
		public System.Data.Linq.Table<property> properties
		{
			get
			{
				return this.GetTable<property>();
			}
		}
		
		public System.Data.Linq.Table<propertyTipe> propertyTipes
		{
			get
			{
				return this.GetTable<propertyTipe>();
			}
		}
		
		public System.Data.Linq.Table<tPembelian> tPembelians
		{
			get
			{
				return this.GetTable<tPembelian>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.client")]
	public partial class client : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idClient;
		
		private string _nama;
		
		private string _jeniskelamin;
		
		private string _telepon;
		
		private string _email;
		
		private string _alamat;
		
		private EntitySet<tPembelian> _tPembelians;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClientChanging(string value);
    partial void OnidClientChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OnjeniskelaminChanging(string value);
    partial void OnjeniskelaminChanged();
    partial void OnteleponChanging(string value);
    partial void OnteleponChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    #endregion
		
		public client()
		{
			this._tPembelians = new EntitySet<tPembelian>(new Action<tPembelian>(this.attach_tPembelians), new Action<tPembelian>(this.detach_tPembelians));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClient", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idClient
		{
			get
			{
				return this._idClient;
			}
			set
			{
				if ((this._idClient != value))
				{
					this.OnidClientChanging(value);
					this.SendPropertyChanging();
					this._idClient = value;
					this.SendPropertyChanged("idClient");
					this.OnidClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jeniskelamin", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jeniskelamin
		{
			get
			{
				return this._jeniskelamin;
			}
			set
			{
				if ((this._jeniskelamin != value))
				{
					this.OnjeniskelaminChanging(value);
					this.SendPropertyChanging();
					this._jeniskelamin = value;
					this.SendPropertyChanged("jeniskelamin");
					this.OnjeniskelaminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telepon", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string telepon
		{
			get
			{
				return this._telepon;
			}
			set
			{
				if ((this._telepon != value))
				{
					this.OnteleponChanging(value);
					this.SendPropertyChanging();
					this._telepon = value;
					this.SendPropertyChanged("telepon");
					this.OnteleponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="client_tPembelian", Storage="_tPembelians", ThisKey="idClient", OtherKey="idClient")]
		public EntitySet<tPembelian> tPembelians
		{
			get
			{
				return this._tPembelians;
			}
			set
			{
				this._tPembelians.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tPembelians(tPembelian entity)
		{
			this.SendPropertyChanging();
			entity.client = this;
		}
		
		private void detach_tPembelians(tPembelian entity)
		{
			this.SendPropertyChanging();
			entity.client = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jabatan")]
	public partial class jabatan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idJabatan;
		
		private string _jabatan1;
		
		private EntitySet<pegawai> _pegawais;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidJabatanChanging(string value);
    partial void OnidJabatanChanged();
    partial void Onjabatan1Changing(string value);
    partial void Onjabatan1Changed();
    #endregion
		
		public jabatan()
		{
			this._pegawais = new EntitySet<pegawai>(new Action<pegawai>(this.attach_pegawais), new Action<pegawai>(this.detach_pegawais));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idJabatan", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idJabatan
		{
			get
			{
				return this._idJabatan;
			}
			set
			{
				if ((this._idJabatan != value))
				{
					this.OnidJabatanChanging(value);
					this.SendPropertyChanging();
					this._idJabatan = value;
					this.SendPropertyChanged("idJabatan");
					this.OnidJabatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="jabatan", Storage="_jabatan1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jabatan1
		{
			get
			{
				return this._jabatan1;
			}
			set
			{
				if ((this._jabatan1 != value))
				{
					this.Onjabatan1Changing(value);
					this.SendPropertyChanging();
					this._jabatan1 = value;
					this.SendPropertyChanged("jabatan1");
					this.Onjabatan1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jabatan_pegawai", Storage="_pegawais", ThisKey="idJabatan", OtherKey="idJabatan")]
		public EntitySet<pegawai> pegawais
		{
			get
			{
				return this._pegawais;
			}
			set
			{
				this._pegawais.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pegawais(pegawai entity)
		{
			this.SendPropertyChanging();
			entity.jabatan1 = this;
		}
		
		private void detach_pegawais(pegawai entity)
		{
			this.SendPropertyChanging();
			entity.jabatan1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kategoriBayar")]
	public partial class kategoriBayar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idKategoriBayar;
		
		private string _kategoriBayar1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidKategoriBayarChanging(string value);
    partial void OnidKategoriBayarChanged();
    partial void OnkategoriBayar1Changing(string value);
    partial void OnkategoriBayar1Changed();
    #endregion
		
		public kategoriBayar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKategoriBayar", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idKategoriBayar
		{
			get
			{
				return this._idKategoriBayar;
			}
			set
			{
				if ((this._idKategoriBayar != value))
				{
					this.OnidKategoriBayarChanging(value);
					this.SendPropertyChanging();
					this._idKategoriBayar = value;
					this.SendPropertyChanged("idKategoriBayar");
					this.OnidKategoriBayarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="kategoriBayar", Storage="_kategoriBayar1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string kategoriBayar1
		{
			get
			{
				return this._kategoriBayar1;
			}
			set
			{
				if ((this._kategoriBayar1 != value))
				{
					this.OnkategoriBayar1Changing(value);
					this.SendPropertyChanging();
					this._kategoriBayar1 = value;
					this.SendPropertyChanged("kategoriBayar1");
					this.OnkategoriBayar1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kategoriCicilan")]
	public partial class kategoriCicilan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idCicilan;
		
		private string _JenisCicilan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCicilanChanging(string value);
    partial void OnidCicilanChanged();
    partial void OnJenisCicilanChanging(string value);
    partial void OnJenisCicilanChanged();
    #endregion
		
		public kategoriCicilan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCicilan", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idCicilan
		{
			get
			{
				return this._idCicilan;
			}
			set
			{
				if ((this._idCicilan != value))
				{
					this.OnidCicilanChanging(value);
					this.SendPropertyChanging();
					this._idCicilan = value;
					this.SendPropertyChanged("idCicilan");
					this.OnidCicilanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JenisCicilan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string JenisCicilan
		{
			get
			{
				return this._JenisCicilan;
			}
			set
			{
				if ((this._JenisCicilan != value))
				{
					this.OnJenisCicilanChanging(value);
					this.SendPropertyChanging();
					this._JenisCicilan = value;
					this.SendPropertyChanged("JenisCicilan");
					this.OnJenisCicilanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pegawai")]
	public partial class pegawai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idPegawai;
		
		private string _nama;
		
		private string _jeniskelamin;
		
		private string _username;
		
		private string _password;
		
		private string _idJabatan;
		
		private string _jabatan;
		
		private EntityRef<jabatan> _jabatan1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPegawaiChanging(string value);
    partial void OnidPegawaiChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OnjeniskelaminChanging(string value);
    partial void OnjeniskelaminChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnidJabatanChanging(string value);
    partial void OnidJabatanChanged();
    partial void OnjabatanChanging(string value);
    partial void OnjabatanChanged();
    #endregion
		
		public pegawai()
		{
			this._jabatan1 = default(EntityRef<jabatan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPegawai", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPegawai
		{
			get
			{
				return this._idPegawai;
			}
			set
			{
				if ((this._idPegawai != value))
				{
					this.OnidPegawaiChanging(value);
					this.SendPropertyChanging();
					this._idPegawai = value;
					this.SendPropertyChanged("idPegawai");
					this.OnidPegawaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jeniskelamin", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jeniskelamin
		{
			get
			{
				return this._jeniskelamin;
			}
			set
			{
				if ((this._jeniskelamin != value))
				{
					this.OnjeniskelaminChanging(value);
					this.SendPropertyChanging();
					this._jeniskelamin = value;
					this.SendPropertyChanged("jeniskelamin");
					this.OnjeniskelaminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idJabatan", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idJabatan
		{
			get
			{
				return this._idJabatan;
			}
			set
			{
				if ((this._idJabatan != value))
				{
					if (this._jabatan1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidJabatanChanging(value);
					this.SendPropertyChanging();
					this._idJabatan = value;
					this.SendPropertyChanged("idJabatan");
					this.OnidJabatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jabatan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jabatan
		{
			get
			{
				return this._jabatan;
			}
			set
			{
				if ((this._jabatan != value))
				{
					this.OnjabatanChanging(value);
					this.SendPropertyChanging();
					this._jabatan = value;
					this.SendPropertyChanged("jabatan");
					this.OnjabatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jabatan_pegawai", Storage="_jabatan1", ThisKey="idJabatan", OtherKey="idJabatan", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public jabatan jabatan1
		{
			get
			{
				return this._jabatan1.Entity;
			}
			set
			{
				jabatan previousValue = this._jabatan1.Entity;
				if (((previousValue != value) 
							|| (this._jabatan1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._jabatan1.Entity = null;
						previousValue.pegawais.Remove(this);
					}
					this._jabatan1.Entity = value;
					if ((value != null))
					{
						value.pegawais.Add(this);
						this._idJabatan = value.idJabatan;
					}
					else
					{
						this._idJabatan = default(string);
					}
					this.SendPropertyChanged("jabatan1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pemilik")]
	public partial class pemilik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idPemilik;
		
		private string _nama;
		
		private string _jeniskelamin;
		
		private string _telepon;
		
		private string _email;
		
		private string _alamat;
		
		private EntitySet<property> _properties;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPemilikChanging(string value);
    partial void OnidPemilikChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OnjeniskelaminChanging(string value);
    partial void OnjeniskelaminChanged();
    partial void OnteleponChanging(string value);
    partial void OnteleponChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    #endregion
		
		public pemilik()
		{
			this._properties = new EntitySet<property>(new Action<property>(this.attach_properties), new Action<property>(this.detach_properties));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPemilik", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPemilik
		{
			get
			{
				return this._idPemilik;
			}
			set
			{
				if ((this._idPemilik != value))
				{
					this.OnidPemilikChanging(value);
					this.SendPropertyChanging();
					this._idPemilik = value;
					this.SendPropertyChanged("idPemilik");
					this.OnidPemilikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jeniskelamin", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jeniskelamin
		{
			get
			{
				return this._jeniskelamin;
			}
			set
			{
				if ((this._jeniskelamin != value))
				{
					this.OnjeniskelaminChanging(value);
					this.SendPropertyChanging();
					this._jeniskelamin = value;
					this.SendPropertyChanged("jeniskelamin");
					this.OnjeniskelaminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telepon", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string telepon
		{
			get
			{
				return this._telepon;
			}
			set
			{
				if ((this._telepon != value))
				{
					this.OnteleponChanging(value);
					this.SendPropertyChanging();
					this._telepon = value;
					this.SendPropertyChanged("telepon");
					this.OnteleponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pemilik_property", Storage="_properties", ThisKey="idPemilik", OtherKey="idPemilik")]
		public EntitySet<property> properties
		{
			get
			{
				return this._properties;
			}
			set
			{
				this._properties.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_properties(property entity)
		{
			this.SendPropertyChanging();
			entity.pemilik = this;
		}
		
		private void detach_properties(property entity)
		{
			this.SendPropertyChanging();
			entity.pemilik = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.property")]
	public partial class property : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idProperty;
		
		private string _namaProperty;
		
		private string _idTipe;
		
		private string _idPemilik;
		
		private string _namaPemilik;
		
		private string _ukuran;
		
		private System.Data.Linq.Binary _gambar;
		
		private string _fasilitas;
		
		private decimal _harga;
		
		private EntitySet<tPembelian> _tPembelians;
		
		private EntityRef<pemilik> _pemilik;
		
		private EntityRef<propertyTipe> _propertyTipe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPropertyChanging(string value);
    partial void OnidPropertyChanged();
    partial void OnnamaPropertyChanging(string value);
    partial void OnnamaPropertyChanged();
    partial void OnidTipeChanging(string value);
    partial void OnidTipeChanged();
    partial void OnidPemilikChanging(string value);
    partial void OnidPemilikChanged();
    partial void OnnamaPemilikChanging(string value);
    partial void OnnamaPemilikChanged();
    partial void OnukuranChanging(string value);
    partial void OnukuranChanged();
    partial void OngambarChanging(System.Data.Linq.Binary value);
    partial void OngambarChanged();
    partial void OnfasilitasChanging(string value);
    partial void OnfasilitasChanged();
    partial void OnhargaChanging(decimal value);
    partial void OnhargaChanged();
    #endregion
		
		public property()
		{
			this._tPembelians = new EntitySet<tPembelian>(new Action<tPembelian>(this.attach_tPembelians), new Action<tPembelian>(this.detach_tPembelians));
			this._pemilik = default(EntityRef<pemilik>);
			this._propertyTipe = default(EntityRef<propertyTipe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProperty", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idProperty
		{
			get
			{
				return this._idProperty;
			}
			set
			{
				if ((this._idProperty != value))
				{
					this.OnidPropertyChanging(value);
					this.SendPropertyChanging();
					this._idProperty = value;
					this.SendPropertyChanged("idProperty");
					this.OnidPropertyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namaProperty", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string namaProperty
		{
			get
			{
				return this._namaProperty;
			}
			set
			{
				if ((this._namaProperty != value))
				{
					this.OnnamaPropertyChanging(value);
					this.SendPropertyChanging();
					this._namaProperty = value;
					this.SendPropertyChanged("namaProperty");
					this.OnnamaPropertyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipe", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idTipe
		{
			get
			{
				return this._idTipe;
			}
			set
			{
				if ((this._idTipe != value))
				{
					if (this._propertyTipe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipeChanging(value);
					this.SendPropertyChanging();
					this._idTipe = value;
					this.SendPropertyChanged("idTipe");
					this.OnidTipeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPemilik", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idPemilik
		{
			get
			{
				return this._idPemilik;
			}
			set
			{
				if ((this._idPemilik != value))
				{
					if (this._pemilik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPemilikChanging(value);
					this.SendPropertyChanging();
					this._idPemilik = value;
					this.SendPropertyChanged("idPemilik");
					this.OnidPemilikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namaPemilik", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string namaPemilik
		{
			get
			{
				return this._namaPemilik;
			}
			set
			{
				if ((this._namaPemilik != value))
				{
					this.OnnamaPemilikChanging(value);
					this.SendPropertyChanging();
					this._namaPemilik = value;
					this.SendPropertyChanged("namaPemilik");
					this.OnnamaPemilikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ukuran", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ukuran
		{
			get
			{
				return this._ukuran;
			}
			set
			{
				if ((this._ukuran != value))
				{
					this.OnukuranChanging(value);
					this.SendPropertyChanging();
					this._ukuran = value;
					this.SendPropertyChanged("ukuran");
					this.OnukuranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gambar", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary gambar
		{
			get
			{
				return this._gambar;
			}
			set
			{
				if ((this._gambar != value))
				{
					this.OngambarChanging(value);
					this.SendPropertyChanging();
					this._gambar = value;
					this.SendPropertyChanged("gambar");
					this.OngambarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fasilitas", DbType="VarChar(100)")]
		public string fasilitas
		{
			get
			{
				return this._fasilitas;
			}
			set
			{
				if ((this._fasilitas != value))
				{
					this.OnfasilitasChanging(value);
					this.SendPropertyChanging();
					this._fasilitas = value;
					this.SendPropertyChanged("fasilitas");
					this.OnfasilitasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harga", DbType="Money NOT NULL")]
		public decimal harga
		{
			get
			{
				return this._harga;
			}
			set
			{
				if ((this._harga != value))
				{
					this.OnhargaChanging(value);
					this.SendPropertyChanging();
					this._harga = value;
					this.SendPropertyChanged("harga");
					this.OnhargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="property_tPembelian", Storage="_tPembelians", ThisKey="idProperty", OtherKey="idProperty")]
		public EntitySet<tPembelian> tPembelians
		{
			get
			{
				return this._tPembelians;
			}
			set
			{
				this._tPembelians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pemilik_property", Storage="_pemilik", ThisKey="idPemilik", OtherKey="idPemilik", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public pemilik pemilik
		{
			get
			{
				return this._pemilik.Entity;
			}
			set
			{
				pemilik previousValue = this._pemilik.Entity;
				if (((previousValue != value) 
							|| (this._pemilik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pemilik.Entity = null;
						previousValue.properties.Remove(this);
					}
					this._pemilik.Entity = value;
					if ((value != null))
					{
						value.properties.Add(this);
						this._idPemilik = value.idPemilik;
					}
					else
					{
						this._idPemilik = default(string);
					}
					this.SendPropertyChanged("pemilik");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="propertyTipe_property", Storage="_propertyTipe", ThisKey="idTipe", OtherKey="idTipe", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public propertyTipe propertyTipe
		{
			get
			{
				return this._propertyTipe.Entity;
			}
			set
			{
				propertyTipe previousValue = this._propertyTipe.Entity;
				if (((previousValue != value) 
							|| (this._propertyTipe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._propertyTipe.Entity = null;
						previousValue.properties.Remove(this);
					}
					this._propertyTipe.Entity = value;
					if ((value != null))
					{
						value.properties.Add(this);
						this._idTipe = value.idTipe;
					}
					else
					{
						this._idTipe = default(string);
					}
					this.SendPropertyChanged("propertyTipe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tPembelians(tPembelian entity)
		{
			this.SendPropertyChanging();
			entity.property = this;
		}
		
		private void detach_tPembelians(tPembelian entity)
		{
			this.SendPropertyChanging();
			entity.property = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.propertyTipe")]
	public partial class propertyTipe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idTipe;
		
		private string _nama;
		
		private string _deskripsi;
		
		private EntitySet<property> _properties;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipeChanging(string value);
    partial void OnidTipeChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OndeskripsiChanging(string value);
    partial void OndeskripsiChanged();
    #endregion
		
		public propertyTipe()
		{
			this._properties = new EntitySet<property>(new Action<property>(this.attach_properties), new Action<property>(this.detach_properties));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipe", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idTipe
		{
			get
			{
				return this._idTipe;
			}
			set
			{
				if ((this._idTipe != value))
				{
					this.OnidTipeChanging(value);
					this.SendPropertyChanging();
					this._idTipe = value;
					this.SendPropertyChanged("idTipe");
					this.OnidTipeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deskripsi", DbType="VarChar(100)")]
		public string deskripsi
		{
			get
			{
				return this._deskripsi;
			}
			set
			{
				if ((this._deskripsi != value))
				{
					this.OndeskripsiChanging(value);
					this.SendPropertyChanging();
					this._deskripsi = value;
					this.SendPropertyChanged("deskripsi");
					this.OndeskripsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="propertyTipe_property", Storage="_properties", ThisKey="idTipe", OtherKey="idTipe")]
		public EntitySet<property> properties
		{
			get
			{
				return this._properties;
			}
			set
			{
				this._properties.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_properties(property entity)
		{
			this.SendPropertyChanging();
			entity.propertyTipe = this;
		}
		
		private void detach_properties(property entity)
		{
			this.SendPropertyChanging();
			entity.propertyTipe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tPembelian")]
	public partial class tPembelian : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idTBeli;
		
		private string _idProperty;
		
		private string _idClient;
		
		private string _namaClient;
		
		private string _idPemilik;
		
		private string _idKategoriBayar;
		
		private string _idCicilan;
		
		private System.DateTime _tanggal;
		
		private decimal _total;
		
		private EntityRef<client> _client;
		
		private EntityRef<property> _property;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTBeliChanging(string value);
    partial void OnidTBeliChanged();
    partial void OnidPropertyChanging(string value);
    partial void OnidPropertyChanged();
    partial void OnidClientChanging(string value);
    partial void OnidClientChanged();
    partial void OnnamaClientChanging(string value);
    partial void OnnamaClientChanged();
    partial void OnidPemilikChanging(string value);
    partial void OnidPemilikChanged();
    partial void OnidKategoriBayarChanging(string value);
    partial void OnidKategoriBayarChanged();
    partial void OnidCicilanChanging(string value);
    partial void OnidCicilanChanged();
    partial void OntanggalChanging(System.DateTime value);
    partial void OntanggalChanged();
    partial void OntotalChanging(decimal value);
    partial void OntotalChanged();
    #endregion
		
		public tPembelian()
		{
			this._client = default(EntityRef<client>);
			this._property = default(EntityRef<property>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTBeli", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idTBeli
		{
			get
			{
				return this._idTBeli;
			}
			set
			{
				if ((this._idTBeli != value))
				{
					this.OnidTBeliChanging(value);
					this.SendPropertyChanging();
					this._idTBeli = value;
					this.SendPropertyChanged("idTBeli");
					this.OnidTBeliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProperty", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idProperty
		{
			get
			{
				return this._idProperty;
			}
			set
			{
				if ((this._idProperty != value))
				{
					if (this._property.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPropertyChanging(value);
					this.SendPropertyChanging();
					this._idProperty = value;
					this.SendPropertyChanged("idProperty");
					this.OnidPropertyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClient", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idClient
		{
			get
			{
				return this._idClient;
			}
			set
			{
				if ((this._idClient != value))
				{
					if (this._client.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidClientChanging(value);
					this.SendPropertyChanging();
					this._idClient = value;
					this.SendPropertyChanged("idClient");
					this.OnidClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namaClient", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string namaClient
		{
			get
			{
				return this._namaClient;
			}
			set
			{
				if ((this._namaClient != value))
				{
					this.OnnamaClientChanging(value);
					this.SendPropertyChanging();
					this._namaClient = value;
					this.SendPropertyChanged("namaClient");
					this.OnnamaClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPemilik", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idPemilik
		{
			get
			{
				return this._idPemilik;
			}
			set
			{
				if ((this._idPemilik != value))
				{
					this.OnidPemilikChanging(value);
					this.SendPropertyChanging();
					this._idPemilik = value;
					this.SendPropertyChanged("idPemilik");
					this.OnidPemilikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKategoriBayar", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idKategoriBayar
		{
			get
			{
				return this._idKategoriBayar;
			}
			set
			{
				if ((this._idKategoriBayar != value))
				{
					this.OnidKategoriBayarChanging(value);
					this.SendPropertyChanging();
					this._idKategoriBayar = value;
					this.SendPropertyChanged("idKategoriBayar");
					this.OnidKategoriBayarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCicilan", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idCicilan
		{
			get
			{
				return this._idCicilan;
			}
			set
			{
				if ((this._idCicilan != value))
				{
					this.OnidCicilanChanging(value);
					this.SendPropertyChanging();
					this._idCicilan = value;
					this.SendPropertyChanged("idCicilan");
					this.OnidCicilanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="Date NOT NULL")]
		public System.DateTime tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this.OntanggalChanging(value);
					this.SendPropertyChanging();
					this._tanggal = value;
					this.SendPropertyChanged("tanggal");
					this.OntanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Money NOT NULL")]
		public decimal total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="client_tPembelian", Storage="_client", ThisKey="idClient", OtherKey="idClient", IsForeignKey=true)]
		public client client
		{
			get
			{
				return this._client.Entity;
			}
			set
			{
				client previousValue = this._client.Entity;
				if (((previousValue != value) 
							|| (this._client.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._client.Entity = null;
						previousValue.tPembelians.Remove(this);
					}
					this._client.Entity = value;
					if ((value != null))
					{
						value.tPembelians.Add(this);
						this._idClient = value.idClient;
					}
					else
					{
						this._idClient = default(string);
					}
					this.SendPropertyChanged("client");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="property_tPembelian", Storage="_property", ThisKey="idProperty", OtherKey="idProperty", IsForeignKey=true)]
		public property property
		{
			get
			{
				return this._property.Entity;
			}
			set
			{
				property previousValue = this._property.Entity;
				if (((previousValue != value) 
							|| (this._property.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._property.Entity = null;
						previousValue.tPembelians.Remove(this);
					}
					this._property.Entity = value;
					if ((value != null))
					{
						value.tPembelians.Add(this);
						this._idProperty = value.idProperty;
					}
					else
					{
						this._idProperty = default(string);
					}
					this.SendPropertyChanged("property");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
