<?xml version="1.0" encoding="utf-8"?><Database Name="RealEstate" Class="REALESTATEDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WINDOWS-LD56BQV;Initial Catalog=RealEstate;Integrated Security=True" SettingsObjectName="TA_RealEstate_Kel11.Properties.Settings" SettingsPropertyName="RealEstateConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.client" Member="clients">
    <Type Name="client">
      <Column Name="idClient" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nama" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="jeniskelamin" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telepon" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="alamat" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="client_tPembelian" Member="tPembelians" ThisKey="idClient" OtherKey="idClient" Type="tPembelian" />
      <Association Name="client_tPenyewaan" Member="tPenyewaans" ThisKey="idClient" OtherKey="idClient" Type="tPenyewaan" />
    </Type>
  </Table>
  <Table Name="dbo.jabatan" Member="jabatans">
    <Type Name="jabatan">
      <Column Name="idJabatan" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="jabatan" Member="jabatan1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="jabatan_pegawai" Member="pegawais" ThisKey="idJabatan" OtherKey="idJabatan" Type="pegawai" />
    </Type>
  </Table>
  <Table Name="dbo.kategoriBayar" Member="kategoriBayars">
    <Type Name="kategoriBayar">
      <Column Name="idKategoriBayar" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="kategoriBayar" Member="kategoriBayar1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="keterangan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kategoriCicilan" Member="kategoriCicilans">
    <Type Name="kategoriCicilan">
      <Column Name="idCicilan" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cicilan" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.pegawai" Member="pegawais">
    <Type Name="pegawai">
      <Column Name="idPegawai" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nama" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="jeniskelamin" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="idJabatan" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="jabatan_pegawai" Member="jabatan" ThisKey="idJabatan" OtherKey="idJabatan" Type="jabatan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.pemilik" Member="pemiliks">
    <Type Name="pemilik">
      <Column Name="idPemilik" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nama" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="jeniskelamin" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telepon" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="alamat" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="pemilik_property" Member="properties" ThisKey="idPemilik" OtherKey="idPemilik" Type="property" />
      <Association Name="pemilik_tPembelian" Member="tPembelians" ThisKey="idPemilik" OtherKey="idPemilik" Type="tPembelian" />
      <Association Name="pemilik_tPenyewaan" Member="tPenyewaans" ThisKey="idPemilik" OtherKey="idPemilik" Type="tPenyewaan" />
    </Type>
  </Table>
  <Table Name="dbo.propertyTipe" Member="propertyTipes">
    <Type Name="propertyTipe">
      <Column Name="idTipe" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nama" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="propertyTipe_property" Member="properties" ThisKey="idTipe" OtherKey="idTipe" Type="property" />
    </Type>
  </Table>
  <Table Name="dbo.property" Member="properties">
    <Type Name="property">
      <Column Name="idProperty" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="namaProperty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idTipe" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="idPemilik" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ukuran" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fasilitas" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="harga" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gambar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="property_tDetailPembelian" Member="tDetailPembelians" ThisKey="idProperty" OtherKey="idProperty" Type="tDetailPembelian" />
      <Association Name="property_tDetailPenyewaan" Member="tDetailPenyewaans" ThisKey="idProperty" OtherKey="idProperty" Type="tDetailPenyewaan" />
      <Association Name="property_tPembelian" Member="tPembelians" ThisKey="idProperty" OtherKey="idProperty" Type="tPembelian" />
      <Association Name="property_tPenyewaan" Member="tPenyewaans" ThisKey="idProperty" OtherKey="idProperty" Type="tPenyewaan" />
      <Association Name="pemilik_property" Member="pemilik" ThisKey="idPemilik" OtherKey="idPemilik" Type="pemilik" IsForeignKey="true" />
      <Association Name="propertyTipe_property" Member="propertyTipe" ThisKey="idTipe" OtherKey="idTipe" Type="propertyTipe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tDetailPembelian" Member="tDetailPembelians">
    <Type Name="tDetailPembelian">
      <Column Name="idTBeli" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idKategoriBayar" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="idCicilan" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="idProperty" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="harga" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lamaCicilan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="property_tDetailPembelian" Member="property" ThisKey="idProperty" OtherKey="idProperty" Type="property" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tDetailPenyewaan" Member="tDetailPenyewaans">
    <Type Name="tDetailPenyewaan">
      <Column Name="idTSewa" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idKategoriBayar" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="idCicilan" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="idProperty" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="mulaiSewa" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="sampai" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="harga" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lamaCicilan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="property_tDetailPenyewaan" Member="property" ThisKey="idProperty" OtherKey="idProperty" Type="property" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tPembelian" Member="tPembelians">
    <Type Name="tPembelian">
      <Column Name="idTBeli" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idProperty" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="idClient" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="idPemilik" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="tanggal" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="client_tPembelian" Member="client" ThisKey="idClient" OtherKey="idClient" Type="client" IsForeignKey="true" />
      <Association Name="pemilik_tPembelian" Member="pemilik" ThisKey="idPemilik" OtherKey="idPemilik" Type="pemilik" IsForeignKey="true" />
      <Association Name="property_tPembelian" Member="property" ThisKey="idProperty" OtherKey="idProperty" Type="property" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tPenyewaan" Member="tPenyewaans">
    <Type Name="tPenyewaan">
      <Column Name="idTSewa" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idProperty" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="idClient" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="idPemilik" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="tanggal" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="client_tPenyewaan" Member="client" ThisKey="idClient" OtherKey="idClient" Type="client" IsForeignKey="true" />
      <Association Name="pemilik_tPenyewaan" Member="pemilik" ThisKey="idPemilik" OtherKey="idPemilik" Type="pemilik" IsForeignKey="true" />
      <Association Name="property_tPenyewaan" Member="property" ThisKey="idProperty" OtherKey="idProperty" Type="property" IsForeignKey="true" />
    </Type>
  </Table>
</Database>