#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TA_RealEstate_Kel11
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RealEstate")]
	public partial class REALESTATEDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertclient(client instance);
    partial void Updateclient(client instance);
    partial void Deleteclient(client instance);
    partial void Insertjabatan(jabatan instance);
    partial void Updatejabatan(jabatan instance);
    partial void Deletejabatan(jabatan instance);
    partial void InsertkategoriBayar(kategoriBayar instance);
    partial void UpdatekategoriBayar(kategoriBayar instance);
    partial void DeletekategoriBayar(kategoriBayar instance);
    partial void InsertkategoriCicilan(kategoriCicilan instance);
    partial void UpdatekategoriCicilan(kategoriCicilan instance);
    partial void DeletekategoriCicilan(kategoriCicilan instance);
    partial void Insertpegawai(pegawai instance);
    partial void Updatepegawai(pegawai instance);
    partial void Deletepegawai(pegawai instance);
    partial void Insertpemilik(pemilik instance);
    partial void Updatepemilik(pemilik instance);
    partial void Deletepemilik(pemilik instance);
    partial void Insertproperty(property instance);
    partial void Updateproperty(property instance);
    partial void Deleteproperty(property instance);
    partial void InsertpropertyTipe(propertyTipe instance);
    partial void UpdatepropertyTipe(propertyTipe instance);
    partial void DeletepropertyTipe(propertyTipe instance);
    partial void InserttDetailPembelian(tDetailPembelian instance);
    partial void UpdatetDetailPembelian(tDetailPembelian instance);
    partial void DeletetDetailPembelian(tDetailPembelian instance);
    partial void InserttDetailPenyewaan(tDetailPenyewaan instance);
    partial void UpdatetDetailPenyewaan(tDetailPenyewaan instance);
    partial void DeletetDetailPenyewaan(tDetailPenyewaan instance);
    partial void InserttPembelian(tPembelian instance);
    partial void UpdatetPembelian(tPembelian instance);
    partial void DeletetPembelian(tPembelian instance);
    partial void InserttPenyewaan(tPenyewaan instance);
    partial void UpdatetPenyewaan(tPenyewaan instance);
    partial void DeletetPenyewaan(tPenyewaan instance);
    #endregion
		
		public REALESTATEDataContext() : 
				base(global::TA_RealEstate_Kel11.Properties.Settings.Default.RealEstateConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public REALESTATEDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public REALESTATEDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public REALESTATEDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public REALESTATEDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<client> clients
		{
			get
			{
				return this.GetTable<client>();
			}
		}
		
		public System.Data.Linq.Table<jabatan> jabatans
		{
			get
			{
				return this.GetTable<jabatan>();
			}
		}
		
		public System.Data.Linq.Table<kategoriBayar> kategoriBayars
		{
			get
			{
				return this.GetTable<kategoriBayar>();
			}
		}
		
		public System.Data.Linq.Table<kategoriCicilan> kategoriCicilans
		{
			get
			{
				return this.GetTable<kategoriCicilan>();
			}
		}
		
		public System.Data.Linq.Table<pegawai> pegawais
		{
			get
			{
				return this.GetTable<pegawai>();
			}
		}
		
		public System.Data.Linq.Table<pemilik> pemiliks
		{
			get
			{
				return this.GetTable<pemilik>();
			}
		}
		
		public System.Data.Linq.Table<property> properties
		{
			get
			{
				return this.GetTable<property>();
			}
		}
		
		public System.Data.Linq.Table<propertyTipe> propertyTipes
		{
			get
			{
				return this.GetTable<propertyTipe>();
			}
		}
		
		public System.Data.Linq.Table<tDetailPembelian> tDetailPembelians
		{
			get
			{
				return this.GetTable<tDetailPembelian>();
			}
		}
		
		public System.Data.Linq.Table<tDetailPenyewaan> tDetailPenyewaans
		{
			get
			{
				return this.GetTable<tDetailPenyewaan>();
			}
		}
		
		public System.Data.Linq.Table<tPembelian> tPembelians
		{
			get
			{
				return this.GetTable<tPembelian>();
			}
		}
		
		public System.Data.Linq.Table<tPenyewaan> tPenyewaans
		{
			get
			{
				return this.GetTable<tPenyewaan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.client")]
	public partial class client : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idClient;
		
		private string _nama;
		
		private string _jeniskelamin;
		
		private string _telepon;
		
		private string _email;
		
		private string _alamat;
		
		private EntitySet<tPembelian> _tPembelians;
		
		private EntitySet<tPenyewaan> _tPenyewaans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClientChanging(string value);
    partial void OnidClientChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OnjeniskelaminChanging(string value);
    partial void OnjeniskelaminChanged();
    partial void OnteleponChanging(string value);
    partial void OnteleponChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    #endregion
		
		public client()
		{
			this._tPembelians = new EntitySet<tPembelian>(new Action<tPembelian>(this.attach_tPembelians), new Action<tPembelian>(this.detach_tPembelians));
			this._tPenyewaans = new EntitySet<tPenyewaan>(new Action<tPenyewaan>(this.attach_tPenyewaans), new Action<tPenyewaan>(this.detach_tPenyewaans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClient", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idClient
		{
			get
			{
				return this._idClient;
			}
			set
			{
				if ((this._idClient != value))
				{
					this.OnidClientChanging(value);
					this.SendPropertyChanging();
					this._idClient = value;
					this.SendPropertyChanged("idClient");
					this.OnidClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jeniskelamin", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jeniskelamin
		{
			get
			{
				return this._jeniskelamin;
			}
			set
			{
				if ((this._jeniskelamin != value))
				{
					this.OnjeniskelaminChanging(value);
					this.SendPropertyChanging();
					this._jeniskelamin = value;
					this.SendPropertyChanged("jeniskelamin");
					this.OnjeniskelaminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telepon", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string telepon
		{
			get
			{
				return this._telepon;
			}
			set
			{
				if ((this._telepon != value))
				{
					this.OnteleponChanging(value);
					this.SendPropertyChanging();
					this._telepon = value;
					this.SendPropertyChanged("telepon");
					this.OnteleponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="client_tPembelian", Storage="_tPembelians", ThisKey="idClient", OtherKey="idClient")]
		public EntitySet<tPembelian> tPembelians
		{
			get
			{
				return this._tPembelians;
			}
			set
			{
				this._tPembelians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="client_tPenyewaan", Storage="_tPenyewaans", ThisKey="idClient", OtherKey="idClient")]
		public EntitySet<tPenyewaan> tPenyewaans
		{
			get
			{
				return this._tPenyewaans;
			}
			set
			{
				this._tPenyewaans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tPembelians(tPembelian entity)
		{
			this.SendPropertyChanging();
			entity.client = this;
		}
		
		private void detach_tPembelians(tPembelian entity)
		{
			this.SendPropertyChanging();
			entity.client = null;
		}
		
		private void attach_tPenyewaans(tPenyewaan entity)
		{
			this.SendPropertyChanging();
			entity.client = this;
		}
		
		private void detach_tPenyewaans(tPenyewaan entity)
		{
			this.SendPropertyChanging();
			entity.client = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jabatan")]
	public partial class jabatan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idJabatan;
		
		private string _jabatan1;
		
		private EntitySet<pegawai> _pegawais;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidJabatanChanging(string value);
    partial void OnidJabatanChanged();
    partial void Onjabatan1Changing(string value);
    partial void Onjabatan1Changed();
    #endregion
		
		public jabatan()
		{
			this._pegawais = new EntitySet<pegawai>(new Action<pegawai>(this.attach_pegawais), new Action<pegawai>(this.detach_pegawais));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idJabatan", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idJabatan
		{
			get
			{
				return this._idJabatan;
			}
			set
			{
				if ((this._idJabatan != value))
				{
					this.OnidJabatanChanging(value);
					this.SendPropertyChanging();
					this._idJabatan = value;
					this.SendPropertyChanged("idJabatan");
					this.OnidJabatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="jabatan", Storage="_jabatan1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jabatan1
		{
			get
			{
				return this._jabatan1;
			}
			set
			{
				if ((this._jabatan1 != value))
				{
					this.Onjabatan1Changing(value);
					this.SendPropertyChanging();
					this._jabatan1 = value;
					this.SendPropertyChanged("jabatan1");
					this.Onjabatan1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jabatan_pegawai", Storage="_pegawais", ThisKey="idJabatan", OtherKey="idJabatan")]
		public EntitySet<pegawai> pegawais
		{
			get
			{
				return this._pegawais;
			}
			set
			{
				this._pegawais.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pegawais(pegawai entity)
		{
			this.SendPropertyChanging();
			entity.jabatan = this;
		}
		
		private void detach_pegawais(pegawai entity)
		{
			this.SendPropertyChanging();
			entity.jabatan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kategoriBayar")]
	public partial class kategoriBayar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idKategoriBayar;
		
		private string _kategoriBayar1;
		
		private string _keterangan;
		
		private EntitySet<tDetailPembelian> _tDetailPembelians;
		
		private EntitySet<tDetailPenyewaan> _tDetailPenyewaans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidKategoriBayarChanging(string value);
    partial void OnidKategoriBayarChanged();
    partial void OnkategoriBayar1Changing(string value);
    partial void OnkategoriBayar1Changed();
    partial void OnketeranganChanging(string value);
    partial void OnketeranganChanged();
    #endregion
		
		public kategoriBayar()
		{
			this._tDetailPembelians = new EntitySet<tDetailPembelian>(new Action<tDetailPembelian>(this.attach_tDetailPembelians), new Action<tDetailPembelian>(this.detach_tDetailPembelians));
			this._tDetailPenyewaans = new EntitySet<tDetailPenyewaan>(new Action<tDetailPenyewaan>(this.attach_tDetailPenyewaans), new Action<tDetailPenyewaan>(this.detach_tDetailPenyewaans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKategoriBayar", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idKategoriBayar
		{
			get
			{
				return this._idKategoriBayar;
			}
			set
			{
				if ((this._idKategoriBayar != value))
				{
					this.OnidKategoriBayarChanging(value);
					this.SendPropertyChanging();
					this._idKategoriBayar = value;
					this.SendPropertyChanged("idKategoriBayar");
					this.OnidKategoriBayarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="kategoriBayar", Storage="_kategoriBayar1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string kategoriBayar1
		{
			get
			{
				return this._kategoriBayar1;
			}
			set
			{
				if ((this._kategoriBayar1 != value))
				{
					this.OnkategoriBayar1Changing(value);
					this.SendPropertyChanging();
					this._kategoriBayar1 = value;
					this.SendPropertyChanged("kategoriBayar1");
					this.OnkategoriBayar1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keterangan", DbType="VarChar(50)")]
		public string keterangan
		{
			get
			{
				return this._keterangan;
			}
			set
			{
				if ((this._keterangan != value))
				{
					this.OnketeranganChanging(value);
					this.SendPropertyChanging();
					this._keterangan = value;
					this.SendPropertyChanged("keterangan");
					this.OnketeranganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoriBayar_tDetailPembelian", Storage="_tDetailPembelians", ThisKey="idKategoriBayar", OtherKey="idKategoriBayar")]
		public EntitySet<tDetailPembelian> tDetailPembelians
		{
			get
			{
				return this._tDetailPembelians;
			}
			set
			{
				this._tDetailPembelians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoriBayar_tDetailPenyewaan", Storage="_tDetailPenyewaans", ThisKey="idKategoriBayar", OtherKey="idKategoriBayar")]
		public EntitySet<tDetailPenyewaan> tDetailPenyewaans
		{
			get
			{
				return this._tDetailPenyewaans;
			}
			set
			{
				this._tDetailPenyewaans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tDetailPembelians(tDetailPembelian entity)
		{
			this.SendPropertyChanging();
			entity.kategoriBayar = this;
		}
		
		private void detach_tDetailPembelians(tDetailPembelian entity)
		{
			this.SendPropertyChanging();
			entity.kategoriBayar = null;
		}
		
		private void attach_tDetailPenyewaans(tDetailPenyewaan entity)
		{
			this.SendPropertyChanging();
			entity.kategoriBayar = this;
		}
		
		private void detach_tDetailPenyewaans(tDetailPenyewaan entity)
		{
			this.SendPropertyChanging();
			entity.kategoriBayar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kategoriCicilan")]
	public partial class kategoriCicilan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idCicilan;
		
		private string _cicilan;
		
		private EntitySet<tDetailPembelian> _tDetailPembelians;
		
		private EntitySet<tDetailPenyewaan> _tDetailPenyewaans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCicilanChanging(string value);
    partial void OnidCicilanChanged();
    partial void OncicilanChanging(string value);
    partial void OncicilanChanged();
    #endregion
		
		public kategoriCicilan()
		{
			this._tDetailPembelians = new EntitySet<tDetailPembelian>(new Action<tDetailPembelian>(this.attach_tDetailPembelians), new Action<tDetailPembelian>(this.detach_tDetailPembelians));
			this._tDetailPenyewaans = new EntitySet<tDetailPenyewaan>(new Action<tDetailPenyewaan>(this.attach_tDetailPenyewaans), new Action<tDetailPenyewaan>(this.detach_tDetailPenyewaans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCicilan", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idCicilan
		{
			get
			{
				return this._idCicilan;
			}
			set
			{
				if ((this._idCicilan != value))
				{
					this.OnidCicilanChanging(value);
					this.SendPropertyChanging();
					this._idCicilan = value;
					this.SendPropertyChanged("idCicilan");
					this.OnidCicilanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cicilan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cicilan
		{
			get
			{
				return this._cicilan;
			}
			set
			{
				if ((this._cicilan != value))
				{
					this.OncicilanChanging(value);
					this.SendPropertyChanging();
					this._cicilan = value;
					this.SendPropertyChanged("cicilan");
					this.OncicilanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoriCicilan_tDetailPembelian", Storage="_tDetailPembelians", ThisKey="idCicilan", OtherKey="idCicilan")]
		public EntitySet<tDetailPembelian> tDetailPembelians
		{
			get
			{
				return this._tDetailPembelians;
			}
			set
			{
				this._tDetailPembelians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoriCicilan_tDetailPenyewaan", Storage="_tDetailPenyewaans", ThisKey="idCicilan", OtherKey="idCicilan")]
		public EntitySet<tDetailPenyewaan> tDetailPenyewaans
		{
			get
			{
				return this._tDetailPenyewaans;
			}
			set
			{
				this._tDetailPenyewaans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tDetailPembelians(tDetailPembelian entity)
		{
			this.SendPropertyChanging();
			entity.kategoriCicilan = this;
		}
		
		private void detach_tDetailPembelians(tDetailPembelian entity)
		{
			this.SendPropertyChanging();
			entity.kategoriCicilan = null;
		}
		
		private void attach_tDetailPenyewaans(tDetailPenyewaan entity)
		{
			this.SendPropertyChanging();
			entity.kategoriCicilan = this;
		}
		
		private void detach_tDetailPenyewaans(tDetailPenyewaan entity)
		{
			this.SendPropertyChanging();
			entity.kategoriCicilan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pegawai")]
	public partial class pegawai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idPegawai;
		
		private string _nama;
		
		private string _jeniskelamin;
		
		private string _username;
		
		private string _password;
		
		private string _idJabatan;
		
		private EntityRef<jabatan> _jabatan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPegawaiChanging(string value);
    partial void OnidPegawaiChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OnjeniskelaminChanging(string value);
    partial void OnjeniskelaminChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnidJabatanChanging(string value);
    partial void OnidJabatanChanged();
    #endregion
		
		public pegawai()
		{
			this._jabatan = default(EntityRef<jabatan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPegawai", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPegawai
		{
			get
			{
				return this._idPegawai;
			}
			set
			{
				if ((this._idPegawai != value))
				{
					this.OnidPegawaiChanging(value);
					this.SendPropertyChanging();
					this._idPegawai = value;
					this.SendPropertyChanged("idPegawai");
					this.OnidPegawaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jeniskelamin", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jeniskelamin
		{
			get
			{
				return this._jeniskelamin;
			}
			set
			{
				if ((this._jeniskelamin != value))
				{
					this.OnjeniskelaminChanging(value);
					this.SendPropertyChanging();
					this._jeniskelamin = value;
					this.SendPropertyChanged("jeniskelamin");
					this.OnjeniskelaminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idJabatan", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idJabatan
		{
			get
			{
				return this._idJabatan;
			}
			set
			{
				if ((this._idJabatan != value))
				{
					if (this._jabatan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidJabatanChanging(value);
					this.SendPropertyChanging();
					this._idJabatan = value;
					this.SendPropertyChanged("idJabatan");
					this.OnidJabatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jabatan_pegawai", Storage="_jabatan", ThisKey="idJabatan", OtherKey="idJabatan", IsForeignKey=true)]
		public jabatan jabatan
		{
			get
			{
				return this._jabatan.Entity;
			}
			set
			{
				jabatan previousValue = this._jabatan.Entity;
				if (((previousValue != value) 
							|| (this._jabatan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._jabatan.Entity = null;
						previousValue.pegawais.Remove(this);
					}
					this._jabatan.Entity = value;
					if ((value != null))
					{
						value.pegawais.Add(this);
						this._idJabatan = value.idJabatan;
					}
					else
					{
						this._idJabatan = default(string);
					}
					this.SendPropertyChanged("jabatan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pemilik")]
	public partial class pemilik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idPemilik;
		
		private string _nama;
		
		private string _jeniskelamin;
		
		private string _telepon;
		
		private string _email;
		
		private string _alamat;
		
		private EntitySet<property> _properties;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPemilikChanging(string value);
    partial void OnidPemilikChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OnjeniskelaminChanging(string value);
    partial void OnjeniskelaminChanged();
    partial void OnteleponChanging(string value);
    partial void OnteleponChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    #endregion
		
		public pemilik()
		{
			this._properties = new EntitySet<property>(new Action<property>(this.attach_properties), new Action<property>(this.detach_properties));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPemilik", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPemilik
		{
			get
			{
				return this._idPemilik;
			}
			set
			{
				if ((this._idPemilik != value))
				{
					this.OnidPemilikChanging(value);
					this.SendPropertyChanging();
					this._idPemilik = value;
					this.SendPropertyChanged("idPemilik");
					this.OnidPemilikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jeniskelamin", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jeniskelamin
		{
			get
			{
				return this._jeniskelamin;
			}
			set
			{
				if ((this._jeniskelamin != value))
				{
					this.OnjeniskelaminChanging(value);
					this.SendPropertyChanging();
					this._jeniskelamin = value;
					this.SendPropertyChanged("jeniskelamin");
					this.OnjeniskelaminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telepon", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string telepon
		{
			get
			{
				return this._telepon;
			}
			set
			{
				if ((this._telepon != value))
				{
					this.OnteleponChanging(value);
					this.SendPropertyChanging();
					this._telepon = value;
					this.SendPropertyChanged("telepon");
					this.OnteleponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pemilik_property", Storage="_properties", ThisKey="idPemilik", OtherKey="idPemilik")]
		public EntitySet<property> properties
		{
			get
			{
				return this._properties;
			}
			set
			{
				this._properties.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_properties(property entity)
		{
			this.SendPropertyChanging();
			entity.pemilik = this;
		}
		
		private void detach_properties(property entity)
		{
			this.SendPropertyChanging();
			entity.pemilik = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.property")]
	public partial class property : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idProperty;
		
		private string _namaProperty;
		
		private string _idTipe;
		
		private string _idPemilik;
		
		private string _ukuran;
		
		private string _fasilitas;
		
		private int _harga;
		
		private System.Data.Linq.Binary _gambar;
		
		private EntitySet<tDetailPembelian> _tDetailPembelians;
		
		private EntitySet<tDetailPenyewaan> _tDetailPenyewaans;
		
		private EntitySet<tPembelian> _tPembelians;
		
		private EntitySet<tPenyewaan> _tPenyewaans;
		
		private EntityRef<pemilik> _pemilik;
		
		private EntityRef<propertyTipe> _propertyTipe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPropertyChanging(string value);
    partial void OnidPropertyChanged();
    partial void OnnamaPropertyChanging(string value);
    partial void OnnamaPropertyChanged();
    partial void OnidTipeChanging(string value);
    partial void OnidTipeChanged();
    partial void OnidPemilikChanging(string value);
    partial void OnidPemilikChanged();
    partial void OnukuranChanging(string value);
    partial void OnukuranChanged();
    partial void OnfasilitasChanging(string value);
    partial void OnfasilitasChanged();
    partial void OnhargaChanging(int value);
    partial void OnhargaChanged();
    partial void OngambarChanging(System.Data.Linq.Binary value);
    partial void OngambarChanged();
    #endregion
		
		public property()
		{
			this._tDetailPembelians = new EntitySet<tDetailPembelian>(new Action<tDetailPembelian>(this.attach_tDetailPembelians), new Action<tDetailPembelian>(this.detach_tDetailPembelians));
			this._tDetailPenyewaans = new EntitySet<tDetailPenyewaan>(new Action<tDetailPenyewaan>(this.attach_tDetailPenyewaans), new Action<tDetailPenyewaan>(this.detach_tDetailPenyewaans));
			this._tPembelians = new EntitySet<tPembelian>(new Action<tPembelian>(this.attach_tPembelians), new Action<tPembelian>(this.detach_tPembelians));
			this._tPenyewaans = new EntitySet<tPenyewaan>(new Action<tPenyewaan>(this.attach_tPenyewaans), new Action<tPenyewaan>(this.detach_tPenyewaans));
			this._pemilik = default(EntityRef<pemilik>);
			this._propertyTipe = default(EntityRef<propertyTipe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProperty", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idProperty
		{
			get
			{
				return this._idProperty;
			}
			set
			{
				if ((this._idProperty != value))
				{
					this.OnidPropertyChanging(value);
					this.SendPropertyChanging();
					this._idProperty = value;
					this.SendPropertyChanged("idProperty");
					this.OnidPropertyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namaProperty", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string namaProperty
		{
			get
			{
				return this._namaProperty;
			}
			set
			{
				if ((this._namaProperty != value))
				{
					this.OnnamaPropertyChanging(value);
					this.SendPropertyChanging();
					this._namaProperty = value;
					this.SendPropertyChanged("namaProperty");
					this.OnnamaPropertyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipe", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idTipe
		{
			get
			{
				return this._idTipe;
			}
			set
			{
				if ((this._idTipe != value))
				{
					if (this._propertyTipe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTipeChanging(value);
					this.SendPropertyChanging();
					this._idTipe = value;
					this.SendPropertyChanged("idTipe");
					this.OnidTipeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPemilik", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idPemilik
		{
			get
			{
				return this._idPemilik;
			}
			set
			{
				if ((this._idPemilik != value))
				{
					if (this._pemilik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPemilikChanging(value);
					this.SendPropertyChanging();
					this._idPemilik = value;
					this.SendPropertyChanged("idPemilik");
					this.OnidPemilikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ukuran", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ukuran
		{
			get
			{
				return this._ukuran;
			}
			set
			{
				if ((this._ukuran != value))
				{
					this.OnukuranChanging(value);
					this.SendPropertyChanging();
					this._ukuran = value;
					this.SendPropertyChanged("ukuran");
					this.OnukuranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fasilitas", DbType="VarChar(100)")]
		public string fasilitas
		{
			get
			{
				return this._fasilitas;
			}
			set
			{
				if ((this._fasilitas != value))
				{
					this.OnfasilitasChanging(value);
					this.SendPropertyChanging();
					this._fasilitas = value;
					this.SendPropertyChanged("fasilitas");
					this.OnfasilitasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harga", DbType="Int NOT NULL")]
		public int harga
		{
			get
			{
				return this._harga;
			}
			set
			{
				if ((this._harga != value))
				{
					this.OnhargaChanging(value);
					this.SendPropertyChanging();
					this._harga = value;
					this.SendPropertyChanged("harga");
					this.OnhargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gambar", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary gambar
		{
			get
			{
				return this._gambar;
			}
			set
			{
				if ((this._gambar != value))
				{
					this.OngambarChanging(value);
					this.SendPropertyChanging();
					this._gambar = value;
					this.SendPropertyChanged("gambar");
					this.OngambarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="property_tDetailPembelian", Storage="_tDetailPembelians", ThisKey="idProperty", OtherKey="idProperty")]
		public EntitySet<tDetailPembelian> tDetailPembelians
		{
			get
			{
				return this._tDetailPembelians;
			}
			set
			{
				this._tDetailPembelians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="property_tDetailPenyewaan", Storage="_tDetailPenyewaans", ThisKey="idProperty", OtherKey="idProperty")]
		public EntitySet<tDetailPenyewaan> tDetailPenyewaans
		{
			get
			{
				return this._tDetailPenyewaans;
			}
			set
			{
				this._tDetailPenyewaans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="property_tPembelian", Storage="_tPembelians", ThisKey="idProperty", OtherKey="idProperty")]
		public EntitySet<tPembelian> tPembelians
		{
			get
			{
				return this._tPembelians;
			}
			set
			{
				this._tPembelians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="property_tPenyewaan", Storage="_tPenyewaans", ThisKey="idProperty", OtherKey="idProperty")]
		public EntitySet<tPenyewaan> tPenyewaans
		{
			get
			{
				return this._tPenyewaans;
			}
			set
			{
				this._tPenyewaans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pemilik_property", Storage="_pemilik", ThisKey="idPemilik", OtherKey="idPemilik", IsForeignKey=true)]
		public pemilik pemilik
		{
			get
			{
				return this._pemilik.Entity;
			}
			set
			{
				pemilik previousValue = this._pemilik.Entity;
				if (((previousValue != value) 
							|| (this._pemilik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pemilik.Entity = null;
						previousValue.properties.Remove(this);
					}
					this._pemilik.Entity = value;
					if ((value != null))
					{
						value.properties.Add(this);
						this._idPemilik = value.idPemilik;
					}
					else
					{
						this._idPemilik = default(string);
					}
					this.SendPropertyChanged("pemilik");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="propertyTipe_property", Storage="_propertyTipe", ThisKey="idTipe", OtherKey="idTipe", IsForeignKey=true)]
		public propertyTipe propertyTipe
		{
			get
			{
				return this._propertyTipe.Entity;
			}
			set
			{
				propertyTipe previousValue = this._propertyTipe.Entity;
				if (((previousValue != value) 
							|| (this._propertyTipe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._propertyTipe.Entity = null;
						previousValue.properties.Remove(this);
					}
					this._propertyTipe.Entity = value;
					if ((value != null))
					{
						value.properties.Add(this);
						this._idTipe = value.idTipe;
					}
					else
					{
						this._idTipe = default(string);
					}
					this.SendPropertyChanged("propertyTipe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tDetailPembelians(tDetailPembelian entity)
		{
			this.SendPropertyChanging();
			entity.property = this;
		}
		
		private void detach_tDetailPembelians(tDetailPembelian entity)
		{
			this.SendPropertyChanging();
			entity.property = null;
		}
		
		private void attach_tDetailPenyewaans(tDetailPenyewaan entity)
		{
			this.SendPropertyChanging();
			entity.property = this;
		}
		
		private void detach_tDetailPenyewaans(tDetailPenyewaan entity)
		{
			this.SendPropertyChanging();
			entity.property = null;
		}
		
		private void attach_tPembelians(tPembelian entity)
		{
			this.SendPropertyChanging();
			entity.property = this;
		}
		
		private void detach_tPembelians(tPembelian entity)
		{
			this.SendPropertyChanging();
			entity.property = null;
		}
		
		private void attach_tPenyewaans(tPenyewaan entity)
		{
			this.SendPropertyChanging();
			entity.property = this;
		}
		
		private void detach_tPenyewaans(tPenyewaan entity)
		{
			this.SendPropertyChanging();
			entity.property = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.propertyTipe")]
	public partial class propertyTipe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idTipe;
		
		private string _nama;
		
		private EntitySet<property> _properties;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipeChanging(string value);
    partial void OnidTipeChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    #endregion
		
		public propertyTipe()
		{
			this._properties = new EntitySet<property>(new Action<property>(this.attach_properties), new Action<property>(this.detach_properties));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipe", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idTipe
		{
			get
			{
				return this._idTipe;
			}
			set
			{
				if ((this._idTipe != value))
				{
					this.OnidTipeChanging(value);
					this.SendPropertyChanging();
					this._idTipe = value;
					this.SendPropertyChanged("idTipe");
					this.OnidTipeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="propertyTipe_property", Storage="_properties", ThisKey="idTipe", OtherKey="idTipe")]
		public EntitySet<property> properties
		{
			get
			{
				return this._properties;
			}
			set
			{
				this._properties.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_properties(property entity)
		{
			this.SendPropertyChanging();
			entity.propertyTipe = this;
		}
		
		private void detach_properties(property entity)
		{
			this.SendPropertyChanging();
			entity.propertyTipe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tDetailPembelian")]
	public partial class tDetailPembelian : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idTBeli;
		
		private string _idProperty;
		
		private int _harga;
		
		private string _idKategoriBayar;
		
		private string _idCicilan;
		
		private System.Nullable<int> _lamaCicilan;
		
		private System.Nullable<int> _perBulan;
		
		private System.Nullable<int> _dp;
		
		private int _totalBayar;
		
		private EntityRef<kategoriBayar> _kategoriBayar;
		
		private EntityRef<kategoriCicilan> _kategoriCicilan;
		
		private EntityRef<property> _property;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTBeliChanging(string value);
    partial void OnidTBeliChanged();
    partial void OnidPropertyChanging(string value);
    partial void OnidPropertyChanged();
    partial void OnhargaChanging(int value);
    partial void OnhargaChanged();
    partial void OnidKategoriBayarChanging(string value);
    partial void OnidKategoriBayarChanged();
    partial void OnidCicilanChanging(string value);
    partial void OnidCicilanChanged();
    partial void OnlamaCicilanChanging(System.Nullable<int> value);
    partial void OnlamaCicilanChanged();
    partial void OnperBulanChanging(System.Nullable<int> value);
    partial void OnperBulanChanged();
    partial void OndpChanging(System.Nullable<int> value);
    partial void OndpChanged();
    partial void OntotalBayarChanging(int value);
    partial void OntotalBayarChanged();
    #endregion
		
		public tDetailPembelian()
		{
			this._kategoriBayar = default(EntityRef<kategoriBayar>);
			this._kategoriCicilan = default(EntityRef<kategoriCicilan>);
			this._property = default(EntityRef<property>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTBeli", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idTBeli
		{
			get
			{
				return this._idTBeli;
			}
			set
			{
				if ((this._idTBeli != value))
				{
					this.OnidTBeliChanging(value);
					this.SendPropertyChanging();
					this._idTBeli = value;
					this.SendPropertyChanged("idTBeli");
					this.OnidTBeliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProperty", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idProperty
		{
			get
			{
				return this._idProperty;
			}
			set
			{
				if ((this._idProperty != value))
				{
					if (this._property.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPropertyChanging(value);
					this.SendPropertyChanging();
					this._idProperty = value;
					this.SendPropertyChanged("idProperty");
					this.OnidPropertyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harga", DbType="Int NOT NULL")]
		public int harga
		{
			get
			{
				return this._harga;
			}
			set
			{
				if ((this._harga != value))
				{
					this.OnhargaChanging(value);
					this.SendPropertyChanging();
					this._harga = value;
					this.SendPropertyChanged("harga");
					this.OnhargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKategoriBayar", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idKategoriBayar
		{
			get
			{
				return this._idKategoriBayar;
			}
			set
			{
				if ((this._idKategoriBayar != value))
				{
					if (this._kategoriBayar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidKategoriBayarChanging(value);
					this.SendPropertyChanging();
					this._idKategoriBayar = value;
					this.SendPropertyChanged("idKategoriBayar");
					this.OnidKategoriBayarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCicilan", DbType="VarChar(5)")]
		public string idCicilan
		{
			get
			{
				return this._idCicilan;
			}
			set
			{
				if ((this._idCicilan != value))
				{
					if (this._kategoriCicilan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCicilanChanging(value);
					this.SendPropertyChanging();
					this._idCicilan = value;
					this.SendPropertyChanged("idCicilan");
					this.OnidCicilanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lamaCicilan", DbType="Int")]
		public System.Nullable<int> lamaCicilan
		{
			get
			{
				return this._lamaCicilan;
			}
			set
			{
				if ((this._lamaCicilan != value))
				{
					this.OnlamaCicilanChanging(value);
					this.SendPropertyChanging();
					this._lamaCicilan = value;
					this.SendPropertyChanged("lamaCicilan");
					this.OnlamaCicilanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perBulan", DbType="Int")]
		public System.Nullable<int> perBulan
		{
			get
			{
				return this._perBulan;
			}
			set
			{
				if ((this._perBulan != value))
				{
					this.OnperBulanChanging(value);
					this.SendPropertyChanging();
					this._perBulan = value;
					this.SendPropertyChanged("perBulan");
					this.OnperBulanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dp", DbType="Int")]
		public System.Nullable<int> dp
		{
			get
			{
				return this._dp;
			}
			set
			{
				if ((this._dp != value))
				{
					this.OndpChanging(value);
					this.SendPropertyChanging();
					this._dp = value;
					this.SendPropertyChanged("dp");
					this.OndpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalBayar", DbType="Int NOT NULL")]
		public int totalBayar
		{
			get
			{
				return this._totalBayar;
			}
			set
			{
				if ((this._totalBayar != value))
				{
					this.OntotalBayarChanging(value);
					this.SendPropertyChanging();
					this._totalBayar = value;
					this.SendPropertyChanged("totalBayar");
					this.OntotalBayarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoriBayar_tDetailPembelian", Storage="_kategoriBayar", ThisKey="idKategoriBayar", OtherKey="idKategoriBayar", IsForeignKey=true)]
		public kategoriBayar kategoriBayar
		{
			get
			{
				return this._kategoriBayar.Entity;
			}
			set
			{
				kategoriBayar previousValue = this._kategoriBayar.Entity;
				if (((previousValue != value) 
							|| (this._kategoriBayar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kategoriBayar.Entity = null;
						previousValue.tDetailPembelians.Remove(this);
					}
					this._kategoriBayar.Entity = value;
					if ((value != null))
					{
						value.tDetailPembelians.Add(this);
						this._idKategoriBayar = value.idKategoriBayar;
					}
					else
					{
						this._idKategoriBayar = default(string);
					}
					this.SendPropertyChanged("kategoriBayar");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoriCicilan_tDetailPembelian", Storage="_kategoriCicilan", ThisKey="idCicilan", OtherKey="idCicilan", IsForeignKey=true)]
		public kategoriCicilan kategoriCicilan
		{
			get
			{
				return this._kategoriCicilan.Entity;
			}
			set
			{
				kategoriCicilan previousValue = this._kategoriCicilan.Entity;
				if (((previousValue != value) 
							|| (this._kategoriCicilan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kategoriCicilan.Entity = null;
						previousValue.tDetailPembelians.Remove(this);
					}
					this._kategoriCicilan.Entity = value;
					if ((value != null))
					{
						value.tDetailPembelians.Add(this);
						this._idCicilan = value.idCicilan;
					}
					else
					{
						this._idCicilan = default(string);
					}
					this.SendPropertyChanged("kategoriCicilan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="property_tDetailPembelian", Storage="_property", ThisKey="idProperty", OtherKey="idProperty", IsForeignKey=true)]
		public property property
		{
			get
			{
				return this._property.Entity;
			}
			set
			{
				property previousValue = this._property.Entity;
				if (((previousValue != value) 
							|| (this._property.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._property.Entity = null;
						previousValue.tDetailPembelians.Remove(this);
					}
					this._property.Entity = value;
					if ((value != null))
					{
						value.tDetailPembelians.Add(this);
						this._idProperty = value.idProperty;
					}
					else
					{
						this._idProperty = default(string);
					}
					this.SendPropertyChanged("property");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tDetailPenyewaan")]
	public partial class tDetailPenyewaan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idTSewa;
		
		private string _idProperty;
		
		private int _harga;
		
		private System.DateTime _mulaiSewa;
		
		private System.DateTime _sampai;
		
		private string _idKategoriBayar;
		
		private string _idCicilan;
		
		private System.Nullable<int> _lamaCicilan;
		
		private System.Nullable<int> _perBulan;
		
		private System.Nullable<int> _dp;
		
		private int _totalBayar;
		
		private EntityRef<kategoriBayar> _kategoriBayar;
		
		private EntityRef<kategoriCicilan> _kategoriCicilan;
		
		private EntityRef<property> _property;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTSewaChanging(string value);
    partial void OnidTSewaChanged();
    partial void OnidPropertyChanging(string value);
    partial void OnidPropertyChanged();
    partial void OnhargaChanging(int value);
    partial void OnhargaChanged();
    partial void OnmulaiSewaChanging(System.DateTime value);
    partial void OnmulaiSewaChanged();
    partial void OnsampaiChanging(System.DateTime value);
    partial void OnsampaiChanged();
    partial void OnidKategoriBayarChanging(string value);
    partial void OnidKategoriBayarChanged();
    partial void OnidCicilanChanging(string value);
    partial void OnidCicilanChanged();
    partial void OnlamaCicilanChanging(System.Nullable<int> value);
    partial void OnlamaCicilanChanged();
    partial void OnperBulanChanging(System.Nullable<int> value);
    partial void OnperBulanChanged();
    partial void OndpChanging(System.Nullable<int> value);
    partial void OndpChanged();
    partial void OntotalBayarChanging(int value);
    partial void OntotalBayarChanged();
    #endregion
		
		public tDetailPenyewaan()
		{
			this._kategoriBayar = default(EntityRef<kategoriBayar>);
			this._kategoriCicilan = default(EntityRef<kategoriCicilan>);
			this._property = default(EntityRef<property>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTSewa", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idTSewa
		{
			get
			{
				return this._idTSewa;
			}
			set
			{
				if ((this._idTSewa != value))
				{
					this.OnidTSewaChanging(value);
					this.SendPropertyChanging();
					this._idTSewa = value;
					this.SendPropertyChanged("idTSewa");
					this.OnidTSewaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProperty", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idProperty
		{
			get
			{
				return this._idProperty;
			}
			set
			{
				if ((this._idProperty != value))
				{
					if (this._property.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPropertyChanging(value);
					this.SendPropertyChanging();
					this._idProperty = value;
					this.SendPropertyChanged("idProperty");
					this.OnidPropertyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harga", DbType="Int NOT NULL")]
		public int harga
		{
			get
			{
				return this._harga;
			}
			set
			{
				if ((this._harga != value))
				{
					this.OnhargaChanging(value);
					this.SendPropertyChanging();
					this._harga = value;
					this.SendPropertyChanged("harga");
					this.OnhargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mulaiSewa", DbType="Date NOT NULL")]
		public System.DateTime mulaiSewa
		{
			get
			{
				return this._mulaiSewa;
			}
			set
			{
				if ((this._mulaiSewa != value))
				{
					this.OnmulaiSewaChanging(value);
					this.SendPropertyChanging();
					this._mulaiSewa = value;
					this.SendPropertyChanged("mulaiSewa");
					this.OnmulaiSewaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sampai", DbType="Date NOT NULL")]
		public System.DateTime sampai
		{
			get
			{
				return this._sampai;
			}
			set
			{
				if ((this._sampai != value))
				{
					this.OnsampaiChanging(value);
					this.SendPropertyChanging();
					this._sampai = value;
					this.SendPropertyChanged("sampai");
					this.OnsampaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKategoriBayar", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idKategoriBayar
		{
			get
			{
				return this._idKategoriBayar;
			}
			set
			{
				if ((this._idKategoriBayar != value))
				{
					if (this._kategoriBayar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidKategoriBayarChanging(value);
					this.SendPropertyChanging();
					this._idKategoriBayar = value;
					this.SendPropertyChanged("idKategoriBayar");
					this.OnidKategoriBayarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCicilan", DbType="VarChar(5)")]
		public string idCicilan
		{
			get
			{
				return this._idCicilan;
			}
			set
			{
				if ((this._idCicilan != value))
				{
					if (this._kategoriCicilan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCicilanChanging(value);
					this.SendPropertyChanging();
					this._idCicilan = value;
					this.SendPropertyChanged("idCicilan");
					this.OnidCicilanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lamaCicilan", DbType="Int")]
		public System.Nullable<int> lamaCicilan
		{
			get
			{
				return this._lamaCicilan;
			}
			set
			{
				if ((this._lamaCicilan != value))
				{
					this.OnlamaCicilanChanging(value);
					this.SendPropertyChanging();
					this._lamaCicilan = value;
					this.SendPropertyChanged("lamaCicilan");
					this.OnlamaCicilanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perBulan", DbType="Int")]
		public System.Nullable<int> perBulan
		{
			get
			{
				return this._perBulan;
			}
			set
			{
				if ((this._perBulan != value))
				{
					this.OnperBulanChanging(value);
					this.SendPropertyChanging();
					this._perBulan = value;
					this.SendPropertyChanged("perBulan");
					this.OnperBulanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dp", DbType="Int")]
		public System.Nullable<int> dp
		{
			get
			{
				return this._dp;
			}
			set
			{
				if ((this._dp != value))
				{
					this.OndpChanging(value);
					this.SendPropertyChanging();
					this._dp = value;
					this.SendPropertyChanged("dp");
					this.OndpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalBayar", DbType="Int NOT NULL")]
		public int totalBayar
		{
			get
			{
				return this._totalBayar;
			}
			set
			{
				if ((this._totalBayar != value))
				{
					this.OntotalBayarChanging(value);
					this.SendPropertyChanging();
					this._totalBayar = value;
					this.SendPropertyChanged("totalBayar");
					this.OntotalBayarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoriBayar_tDetailPenyewaan", Storage="_kategoriBayar", ThisKey="idKategoriBayar", OtherKey="idKategoriBayar", IsForeignKey=true)]
		public kategoriBayar kategoriBayar
		{
			get
			{
				return this._kategoriBayar.Entity;
			}
			set
			{
				kategoriBayar previousValue = this._kategoriBayar.Entity;
				if (((previousValue != value) 
							|| (this._kategoriBayar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kategoriBayar.Entity = null;
						previousValue.tDetailPenyewaans.Remove(this);
					}
					this._kategoriBayar.Entity = value;
					if ((value != null))
					{
						value.tDetailPenyewaans.Add(this);
						this._idKategoriBayar = value.idKategoriBayar;
					}
					else
					{
						this._idKategoriBayar = default(string);
					}
					this.SendPropertyChanged("kategoriBayar");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kategoriCicilan_tDetailPenyewaan", Storage="_kategoriCicilan", ThisKey="idCicilan", OtherKey="idCicilan", IsForeignKey=true)]
		public kategoriCicilan kategoriCicilan
		{
			get
			{
				return this._kategoriCicilan.Entity;
			}
			set
			{
				kategoriCicilan previousValue = this._kategoriCicilan.Entity;
				if (((previousValue != value) 
							|| (this._kategoriCicilan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kategoriCicilan.Entity = null;
						previousValue.tDetailPenyewaans.Remove(this);
					}
					this._kategoriCicilan.Entity = value;
					if ((value != null))
					{
						value.tDetailPenyewaans.Add(this);
						this._idCicilan = value.idCicilan;
					}
					else
					{
						this._idCicilan = default(string);
					}
					this.SendPropertyChanged("kategoriCicilan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="property_tDetailPenyewaan", Storage="_property", ThisKey="idProperty", OtherKey="idProperty", IsForeignKey=true)]
		public property property
		{
			get
			{
				return this._property.Entity;
			}
			set
			{
				property previousValue = this._property.Entity;
				if (((previousValue != value) 
							|| (this._property.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._property.Entity = null;
						previousValue.tDetailPenyewaans.Remove(this);
					}
					this._property.Entity = value;
					if ((value != null))
					{
						value.tDetailPenyewaans.Add(this);
						this._idProperty = value.idProperty;
					}
					else
					{
						this._idProperty = default(string);
					}
					this.SendPropertyChanged("property");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tPembelian")]
	public partial class tPembelian : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idTBeli;
		
		private System.DateTime _tanggal;
		
		private string _idProperty;
		
		private string _idClient;
		
		private System.Nullable<int> _total;
		
		private string _status;
		
		private EntityRef<client> _client;
		
		private EntityRef<property> _property;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTBeliChanging(string value);
    partial void OnidTBeliChanged();
    partial void OntanggalChanging(System.DateTime value);
    partial void OntanggalChanged();
    partial void OnidPropertyChanging(string value);
    partial void OnidPropertyChanged();
    partial void OnidClientChanging(string value);
    partial void OnidClientChanged();
    partial void OntotalChanging(System.Nullable<int> value);
    partial void OntotalChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public tPembelian()
		{
			this._client = default(EntityRef<client>);
			this._property = default(EntityRef<property>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTBeli", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idTBeli
		{
			get
			{
				return this._idTBeli;
			}
			set
			{
				if ((this._idTBeli != value))
				{
					this.OnidTBeliChanging(value);
					this.SendPropertyChanging();
					this._idTBeli = value;
					this.SendPropertyChanged("idTBeli");
					this.OnidTBeliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="Date NOT NULL")]
		public System.DateTime tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this.OntanggalChanging(value);
					this.SendPropertyChanging();
					this._tanggal = value;
					this.SendPropertyChanged("tanggal");
					this.OntanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProperty", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idProperty
		{
			get
			{
				return this._idProperty;
			}
			set
			{
				if ((this._idProperty != value))
				{
					if (this._property.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPropertyChanging(value);
					this.SendPropertyChanging();
					this._idProperty = value;
					this.SendPropertyChanged("idProperty");
					this.OnidPropertyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClient", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idClient
		{
			get
			{
				return this._idClient;
			}
			set
			{
				if ((this._idClient != value))
				{
					if (this._client.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidClientChanging(value);
					this.SendPropertyChanging();
					this._idClient = value;
					this.SendPropertyChanged("idClient");
					this.OnidClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(5)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="client_tPembelian", Storage="_client", ThisKey="idClient", OtherKey="idClient", IsForeignKey=true)]
		public client client
		{
			get
			{
				return this._client.Entity;
			}
			set
			{
				client previousValue = this._client.Entity;
				if (((previousValue != value) 
							|| (this._client.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._client.Entity = null;
						previousValue.tPembelians.Remove(this);
					}
					this._client.Entity = value;
					if ((value != null))
					{
						value.tPembelians.Add(this);
						this._idClient = value.idClient;
					}
					else
					{
						this._idClient = default(string);
					}
					this.SendPropertyChanged("client");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="property_tPembelian", Storage="_property", ThisKey="idProperty", OtherKey="idProperty", IsForeignKey=true)]
		public property property
		{
			get
			{
				return this._property.Entity;
			}
			set
			{
				property previousValue = this._property.Entity;
				if (((previousValue != value) 
							|| (this._property.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._property.Entity = null;
						previousValue.tPembelians.Remove(this);
					}
					this._property.Entity = value;
					if ((value != null))
					{
						value.tPembelians.Add(this);
						this._idProperty = value.idProperty;
					}
					else
					{
						this._idProperty = default(string);
					}
					this.SendPropertyChanged("property");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tPenyewaan")]
	public partial class tPenyewaan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idTSewa;
		
		private System.DateTime _tanggal;
		
		private string _idProperty;
		
		private string _idClient;
		
		private System.Nullable<int> _total;
		
		private string _status;
		
		private EntityRef<client> _client;
		
		private EntityRef<property> _property;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTSewaChanging(string value);
    partial void OnidTSewaChanged();
    partial void OntanggalChanging(System.DateTime value);
    partial void OntanggalChanged();
    partial void OnidPropertyChanging(string value);
    partial void OnidPropertyChanged();
    partial void OnidClientChanging(string value);
    partial void OnidClientChanged();
    partial void OntotalChanging(System.Nullable<int> value);
    partial void OntotalChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public tPenyewaan()
		{
			this._client = default(EntityRef<client>);
			this._property = default(EntityRef<property>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTSewa", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idTSewa
		{
			get
			{
				return this._idTSewa;
			}
			set
			{
				if ((this._idTSewa != value))
				{
					this.OnidTSewaChanging(value);
					this.SendPropertyChanging();
					this._idTSewa = value;
					this.SendPropertyChanged("idTSewa");
					this.OnidTSewaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="Date NOT NULL")]
		public System.DateTime tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this.OntanggalChanging(value);
					this.SendPropertyChanging();
					this._tanggal = value;
					this.SendPropertyChanged("tanggal");
					this.OntanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProperty", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idProperty
		{
			get
			{
				return this._idProperty;
			}
			set
			{
				if ((this._idProperty != value))
				{
					if (this._property.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPropertyChanging(value);
					this.SendPropertyChanging();
					this._idProperty = value;
					this.SendPropertyChanged("idProperty");
					this.OnidPropertyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClient", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idClient
		{
			get
			{
				return this._idClient;
			}
			set
			{
				if ((this._idClient != value))
				{
					if (this._client.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidClientChanging(value);
					this.SendPropertyChanging();
					this._idClient = value;
					this.SendPropertyChanged("idClient");
					this.OnidClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(5)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="client_tPenyewaan", Storage="_client", ThisKey="idClient", OtherKey="idClient", IsForeignKey=true)]
		public client client
		{
			get
			{
				return this._client.Entity;
			}
			set
			{
				client previousValue = this._client.Entity;
				if (((previousValue != value) 
							|| (this._client.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._client.Entity = null;
						previousValue.tPenyewaans.Remove(this);
					}
					this._client.Entity = value;
					if ((value != null))
					{
						value.tPenyewaans.Add(this);
						this._idClient = value.idClient;
					}
					else
					{
						this._idClient = default(string);
					}
					this.SendPropertyChanged("client");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="property_tPenyewaan", Storage="_property", ThisKey="idProperty", OtherKey="idProperty", IsForeignKey=true)]
		public property property
		{
			get
			{
				return this._property.Entity;
			}
			set
			{
				property previousValue = this._property.Entity;
				if (((previousValue != value) 
							|| (this._property.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._property.Entity = null;
						previousValue.tPenyewaans.Remove(this);
					}
					this._property.Entity = value;
					if ((value != null))
					{
						value.tPenyewaans.Add(this);
						this._idProperty = value.idProperty;
					}
					else
					{
						this._idProperty = default(string);
					}
					this.SendPropertyChanged("property");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
